### PR TITLE
Add a contact feed

### PR DESCRIPTION
**Pull request by heathkit**
For chapter 9, we need something that updates automatically. Having an Observable is also valuable to demonstrate. This change adds a "feed" button to the contact details view that shows the contact's real time social media updates. 

The "Follow" button only shows when there are more than two ~tweets~ non-trademarked social media updates. Clicking it does nothing. The feed automatically shows random updates every 15 seconds or so. Contributions to the list of social media updates are welcome.

### CODE REVIEW

**Comment by cnishina** [comment]
This upgrades to Angular 4. How does this affect the other chapters?

**Comment by jesselpalmer** [comment]
I'm ok with upgrading to Angular 4 since I have to update a lot of the content any. I think @corinna000 would like to continue with Angular 2.4.9 though. @corinna000 would you like to test this out and see if it breaks any of your tests? I don't think the upgrade should change a whole lot.

**Comment by corinna000** [comment]
@jesselpalmer I'll check this out tonight. I've also updated my email filters so that anything for this project goes into my inbox so I don't miss any more notifications!

**Comment by jesselpalmer** [comment]
@corinna000 ok, sounds good. thanks, corinna!

**Comment by heathkit** [comment]
FYI, upgrading to Angular 4 _should_ be fully [backwards compatible](http://angularjs.blogspot.com/2017/03/angular-400-now-available.html) with 2. The only public changes should be around animations.

**Comment by jesselpalmer** [comment]
Sounds good to me. What do you think @corinna000? There shouldn't be any issues.

**Comment by heathkit** [comment]
To be clear, when I say "shouldn't be breaking changes" I mean "boy I sure
hope there aren't any". Lots of people have upgraded to 4 at this point,
but there is always a risk of new bugs or unintentional breaking changes.

**Comment by jesselpalmer** [comment]
I'm clear on that. I probably should have put "shouldn't be" in quotes or something :)

**Comment by corinna000** [comment]
Let's do it.

**Pull request merged**
